version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_net

  web:
    image: localhost:5000/myapp-web:latest
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          memory: 2048M
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - FLASK_ENV=development  # Optional: adds test user
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
    networks:
      - app_net

  nginx:
    image: localhost:5000/myapp-nginx:latest
    deploy:
      mode: global
    ports:
      - "9000:80"
    depends_on:
      - web
    networks:
      - app_net

networks:
  app_net:
    driver: overlay
    attachable: true

volumes:
  db-data: